name: Build project

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Clone source code
        uses: actions/checkout@v4

      - name: Setup .NET sdk
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0'
        
      - name: Restore project
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration=release
